# Copyright rigélblu inc. All rights reserved.

# Put custom env vars or override common ones from ../pipeline.yaml here
env:
  GC_RUN_SERVICE_NAME: mgn-public-site
  GC_PROJECT_ID_DEV: rb-dev-REDACTED
  GC_PROJECT_ID_PROD: rb-prod-REDACTED

steps:
  - group:
    steps:
    - label: 'mgn public site ›'
      command: buildkite-agent pipeline upload .buildkite/apps/default-pipeline.yaml
